### PR TITLE
Dev tempest station

### PR DESCRIPTION
**Pull request by jokerboy**
Mark, (Doug again)

Here's the PR for the integration of the WeatherFlow Tempest station. 

Let me know if you have any issues with the changes.

### CODE REVIEW

**Comment by mcrossley** [comment]
Merged, but a request... Can you respect the original files line endings and tabs please.

By default across the project I am trying to use Unix (LF) line endings and indents use tabs.

Thanks

**Comment by jokerboy** [comment]
Thanks Mark!

I'll fix the line endings & tabs in the next PR

Doug

**Comment by jokerboy** [comment]
Hi Mark,

Are you wanting just the distributionfiles project to have unix file
endings? because as far as I can tell all of the ".cs" files in the
CumulusMX project are using windows line endings.

Thanks,

Doug

**Comment by jokerboy** [comment]
Mark,

I think git/github is converting the line endings to 'lf' when I push the
changes so perhaps the only issue is the tabs.  I'll work to get those
fixed.

Regards,

Doug

**Pull request merged**
