### PR TITLE
Added new Local web files copy path option

### PR DESCRIPTION
**Pull request by bobmoss**
Hi, following my suggestion in the forum, https://cumulus.hosiene.co.uk/viewtopic.php?f=36&t=18265 I've added the option to locally copy the standard web files so they don't need to be added into "Extra web files" all the time.
I've made changes here and in the distribution files.

### CODE REVIEW

**Comment by bobmoss** [comment]
I'm happy to add one in, I left it out as the FTP option works in that way and was wanting to follow the same coding/setting style.
I also considered adding an "Use this path for locally copied extra web files" option, so that you only had to add the base path in once, what do you think?

**Comment by mcrossley** [comment]
I think we keep a new field for the local copy - there may be situations where users want to FTP some files (for example to backup files) and locally copy the web files.

**Comment by bobmoss** [comment]
Ok, I think I know what you are saying - We want a tick box to enable local file copying to the path specified, which would enable local file copying in addition to FTP so they could do both? Is that correct?

**Comment by mcrossley** [comment]
That is correct - I think the extra flexibility is worth the bit of extra effort and another tick box for the users.

I'll close this PR and await another. I do have bigish code change coming up for release 3.7.0. As well as new functionality, I've renamed lots of variables that used inconsistent case with the rest that always bugged me - and made copy/paste/replace of code sections a pain! Merging with that may be painful, so could you hold off the next PR until I push that release?

**Pull request closed without merging**
